name: bi'kaç düşüncenin dijital izdüşümü
description: bi'kaç düşüncenin dijital izdüşümü
meta_description: "kişisel şeyler falan"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://blog.kisa.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'mustafakisa'

# Details for the RSS feed generator
url:            'http://blog.kisa.io'
author:         'Mustafa Kısa'
authorTwitter:  'mustafakisa'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
